version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/ewb
    steps:
      - checkout
      - run: npm --version
      - run: npm install
      - run: npx bower install
      - run: npx tsc --build server/src/tsconfig.json
      - run: npx grunt build
      - run: mv node_modules dist/node_modules
      - run: tar czf dist.tgz dist
      - persist_to_workspace:
          root: ~/ewb
          paths:
            - dist.tgz
  test:
    docker:
      - image: circleci/node
    working_directory: ~/ewb
    steps:
      - checkout
      - run: npm --version
      - run: npm install
      - run: npx tsc --build server/src/tsconfig.json
      - run: npx mocha --config server-dist/test/foo.js server-dist/test/**/*.js server-dist/test/*.js
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/ewb
      - run:
          name: Deploy over SSH
          command: |
            scp ~/ewb/dist.tgz $SSH_USER@$SSH_HOST:~/dist.tgz
            ssh $SSH_USER@$SSH_HOST "./deploy.sh"

workflows:
  version: 2
  build: # build on every branch except master
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - build
  build-and-deploy: # build and deploy iff branch is master
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
